services:
  hngopher:
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: hngopher
    ports:
      - "7070:70"
    volumes:
      - ./:/opt/hngopher/
      - ./public:/var/gopher/
